name: Generate Android Keystore

on:
  workflow_dispatch:
    inputs:
      keystore_password:
        description: 'Mot de passe du keystore (minimum 6 caractères)'
        required: true
        type: string
      key_password:
        description: 'Mot de passe de la clé (peut être identique au keystore)'
        required: true
        type: string
      dname_cn:
        description: 'Prénom et Nom'
        required: true
        type: string
      dname_ou:
        description: 'Unité organisationnelle (ex: Development)'
        required: true
        default: 'Development'
        type: string
      dname_o:
        description: 'Organisation (ex: La Flèche)'
        required: true
        default: 'La Flèche'
        type: string
      dname_l:
        description: 'Ville'
        required: true
        type: string
      dname_st:
        description: 'État/Province'
        required: true
        type: string
      dname_c:
        description: 'Code pays (ex: FR)'
        required: true
        default: 'FR'
        type: string

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -v \
            -storetype PKCS12 \
            -keystore la-fleche-release.keystore \
            -alias la-fleche \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "${{ inputs.keystore_password }}" \
            -keypass "${{ inputs.key_password }}" \
            -dname "CN=${{ inputs.dname_cn }}, OU=${{ inputs.dname_ou }}, O=${{ inputs.dname_o }}, L=${{ inputs.dname_l }}, ST=${{ inputs.dname_st }}, C=${{ inputs.dname_c }}"

      - name: Encode Keystore to Base64
        id: encode
        run: |
          KEYSTORE_BASE64=$(base64 -w 0 la-fleche-release.keystore)
          echo "keystore_base64<<EOF" >> $GITHUB_OUTPUT
          echo "$KEYSTORE_BASE64" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Display Secret Values
        run: |
          echo "✅ Keystore généré avec succès!"
          echo ""
          echo "📝 Configurez ces 4 secrets dans GitHub (Settings → Secrets and variables → Actions):"
          echo "==============================================================================="
          echo ""
          echo "1. ANDROID_KEY_ALIAS"
          echo "   Valeur: la-fleche"
          echo ""
          echo "2. ANDROID_KEYSTORE_PASSWORD"
          echo "   Valeur: (le mot de passe keystore que vous avez entré)"
          echo ""
          echo "3. ANDROID_KEY_PASSWORD"
          echo "   Valeur: (le mot de passe de clé que vous avez entré)"
          echo ""
          echo "4. ANDROID_KEYSTORE_BASE64"
          echo "   Valeur ci-dessous (copiez TOUT le texte):"
          echo "   -------------------------------------------"
          echo "${{ steps.encode.outputs.keystore_base64 }}"
          echo "   -------------------------------------------"
          echo ""
          echo "⚠️  IMPORTANT: Conservez ces informations en lieu sûr!"

      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-keystore
          path: la-fleche-release.keystore
          retention-days: 7
